export const texts = {
    es: {
        titleConfig: "CONFIGURACIÓN",
        matchTime: "Minutos por partido:",
        howManyTeams: "Equipos (Máx 20):",
        goalsToWinLabel: "Goles para ganar (0 = sin límite):",
        noLimit: "Sin límite de goles",
        goalsLimit: "A",
        goalsLimitSuffix: "goles",
        gameMode: "Modo de Juego:",
        start: "CONTINUAR",
        regTitle: "REGISTRO",
        initTorneo: "INICIAR TORNEO",
        draw: "EMPATE",
        won: "GANÓ",
        history: "📜 HISTORIAL",
        statsPos: "POSICIONES",
        statsGoals: "⚽ GOLEADORES",
        statsKicks: "🦵 PATADAS",
        resetAll: "BORRAR TODO",
        resetTable: "LIMPIAR TABLA",
        confirmVictory: "¿Confirmar victoria de",
        confirmDraw: "¿Declarar EMPATE?",
        errorTie: "No podés declarar un ganador si el resultado está empatado.",
        errorNotTie: "No podés declarar empate si hay un equipo con más goles.",
        errorWinner: "El equipo seleccionado no es el que va ganando.",
        teamsInGame: "EN CANCHA:",
        btnEndManual: "FINALIZAR",
        tableCols: ["EQ", "PJ", "G", "E", "P", "GF", "GC", "DG", "PTS"],
        resetTimerConfirm: "¿Reiniciar el tiempo del partido?",
        confirmManualEnd: "¿Finalizar el partido ahora?",
        nextMatch: "Próximo:",
        resting: "Descansa",
        tapToClose: "Toca para cerrar",
        showStats: "📊 VER ESTADÍSTICAS",
        hideStats: "📊 OCULTAR ESTADÍSTICAS",
        resetAllConfirm: "¿Borrar todo el torneo y empezar de cero?"
    },
    en: {
        titleConfig: "SETTINGS",
        matchTime: "Minutes per match:",
        howManyTeams: "Teams (Max 20):",
        goalsToWinLabel: "Goals to win (0 = no limit):",
        noLimit: "No goal limit",
        goalsLimit: "First to",
        goalsLimitSuffix: "goals",
        gameMode: "Game Mode:",
        start: "CONTINUE",
        regTitle: "REGISTRATION",
        initTorneo: "START TOURNAMENT",
        draw: "DRAW",
        won: "WON",
        history: "📜 HISTORY",
        statsPos: "STANDINGS",
        statsGoals: "⚽ TOP SCORERS",
        statsKicks: "🦵 KICKS",
        resetAll: "RESET ALL",
        resetTable: "CLEAR TABLE",
        confirmVictory: "Confirm victory for",
        confirmDraw: "Declare a DRAW?",
        errorTie: "Can't declare a winner if the score is tied.",
        errorNotTie: "Can't declare a draw if one team has more goals.",
        errorWinner: "The selected team is not currently winning.",
        teamsInGame: "ON FIELD:",
        btnEndManual: "FINISH",
        tableCols: ["TM", "GP", "W", "D", "L", "GS", "GA", "GD", "PTS"],
        resetTimerConfirm: "Reset the match timer?",
        confirmManualEnd: "Finish the match now?",
        nextMatch: "Next:",
        resting: "Resting",
        tapToClose: "Tap to close",
        showStats: "📊 VIEW STATS",
        hideStats: "📊 HIDE STATS",
        resetAllConfirm: "Delete the entire tournament and start over?"
    }
};

export const getSaved = (key, def) => {
    try {
        const s = localStorage.getItem(key);
        return s ? JSON.parse(s) : def;
    } catch { return def; }
};
